W5D1/Reddit/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :sessions, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts
  end 

end

W5D1/Reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true
  validates :posts, presence: true
  
  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :sub

  has_many :post_subs

  has_many :posts, through: :post_subs, source: :sub
end

W5D1/Reddit/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  validates :sub_id, :post_id, presence: true 

  belongs_to :post

  belongs_to :sub

end

W5D1/Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts

  has_many :post_subs
end

W5D1/Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, uniqueness: true

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :moderated_subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user :nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(128)
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    if self.session_token
      return self.session_token
    else
      self.session_token = User.generate_session_token
      self.save
     end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

W5D1/Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    user = User.find_by(session_token: session[:session_token])
    user.reset_session_token
    session[:session_token] = nil
    @current_user = nil
  end

  def require_user
    if current_user
     true
    else
      redirect_to new_sessions_url
    end
  end

end

W5D1/Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, only: [:create, :new]
  before_action :is_author?, only: [:update, :edit]

  def new
    @sub_id = params[:sub_id]
    @subs = Sub.all
    render :new
  end

  def create
    @p = Post.new(post_params)
    @p.author_id = current_user.id
  
    if @p.save
      redirect_to post_url(@p)
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to sub_post_url(@post.sub, @post)
    else
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def is_author?
    @post = Post.find_by(id: params[:id])
    if current_user.id == @post.author_id
      return true
    else
      redirect_to sub_post_url(@post.sub, @post)
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

W5D1/Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      session_params[:username], session_params[:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      render :new
    end
  end

  def destroy
    logout if current_user
    redirect_to :new
  end

  private
  def session_params
    params.require(:session).permit(:username, :password)
  end
end

W5D1/Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :is_moderator?, only: [:edit, :update]
  before_action :require_user, only: [:new, :create]
  def new
    @current_user
    render :new
  end

  def index
    @current_user = current_user
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save!
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      render :show
    else
      render :edit
    end
  end

  def is_moderator?
    @sub = Sub.find_by(id: params[:id])
    if current_user.id == @sub.moderator_id
      return true
    else
      redirect_to sub_url(@sub)
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:description, :title)
  end
end

W5D1/Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @u = User.new
    render :new
  end

  def create
    @u = User.new(user_params)
    if @u.save
      login(@u)
      redirect_to subs_url
    else
      flash.now[:errors] = @u.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D1/Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

W5D1/Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

W5D1/Reddit/app/helpers/postsubs_helper.rb
module PostsubsHelper
end

W5D1/Reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

W5D1/Reddit/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

W5D1/Reddit/app/views/posts/edit.html.erb
<form action=" <%= sub_post_url(@post.sub, @post) %> " method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <label for="title">Title</label>
  <input id="title" type="text" name="post[title]" value=" <%= @post.title %> ">
  <br>
  <label for="url">Url</label>
  <input id="url" type="text" name="post[url]" value=" <%= @post.url %> ">
  <br>
  <label for="content">Content</label>
  <textarea id="content" name="post[content]" rows="8" cols="80"><%= @post.content %></textarea>
  <br>
  <input type="submit" value="Edit Post">
</form>

W5D1/Reddit/app/views/posts/new.html.erb
<form action=" <%= sub_posts_url(@sub_id) %> " method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <label for="title">Title</label>
  <input id="title" type="text" name="post[title]">
  <br>
  <label for="url">Url</label>
  <input id="url" type="text" name="post[url]">
  <br>
  <label for="content">Content</label>
  <textarea id="content" name="post[content]" rows="8" cols="80"></textarea>
  <br>

  <label for="subs">Subs</label>
  <input type="hidden" name="post[sub_ids][]" value="">
  <br>
  <% @subs.each do |sub| %>
   <label><%= sub.name %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    <br>
  </label>
  <% end  %>
  <input type="submit" value="Create Post">
</form>

W5D1/Reddit/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>

<% if current_user %>
<%= link_to "Edit Post", edit_sub_post_url(@post.sub, @post) %>
<% end %>

<ul>
  <li> <%= link_to "#{@post.title}", @post.url if @post.url %> </li>
  <li> <%= @post.content %> </li>
</ul>

W5D1/Reddit/app/views/subs/edit.html.erb
<form action= "<%= sub_url(@sub) %>" method="post">

  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <input type="hidden" name="_method" value="PATCH">
  <label for="title">Title</label>
  <input id="title" type="text" name="sub[title]" value="<%= @sub.title %>" >
  <br>
  <label for="description">Description</label>
  <textarea id="description" name="sub[description]" rows="8" cols="80"> <%= @sub.description %> </textarea>
  <br>

  <input type="submit" value="Edit Sub">
</form>

W5D1/Reddit/app/views/subs/index.html.erb
<h1>All Subs</h1>
<%= current_user.username %>
<% if @current_user %>
  <%= link_to "Create New Sub", "/subs/new" %>
<% end  %>

<ul>
  <% @current_user.moderated_subs.each do |sub| %>
    <li><%= link_to "#{sub.title}", sub_url(sub) %></li>
      <ul>
        <li> <%= sub.description %> </li>
      </ul>
  <% end %>
</ul>

W5D1/Reddit/app/views/subs/new.html.erb
<form action="/subs" method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <label for="title">Title</label>
  <input id="title" type="text" name="sub[title]">
  <br>
  <label for="description">Description</label>
  <textarea id="description" name="sub[description]" rows="8" cols="80"> </textarea>
  <br>

  <input type="submit" value="Create Sub">
</form>

W5D1/Reddit/app/views/subs/show.html.erb
<h1><%=@sub.title%></h1>

<h2><%=@sub.description%></h2>

<%= link_to "Back to All Subs", subs_url %>

<br>

<%= link_to "Edit Sub", edit_sub_url(@sub) %>

W5D1/Reddit/app/views/users/new.html.erb
<h1><%= "New user" %></h1>
<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %> ">
  <label for="username">username</label>
  <input id="username" type="text" name="user[username]">
  <br>
  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]">
  <br>

  <input type="submit" value="Create User">
</form>